#!/usr/bin/env bash

PL_SEGMENTS=(
    # Segment                Background  Foreground   Other Args
    # -------                ----------  ----------   ----------
    'literal_segment         Default    BoldBlack     ╭'
    'literal_segment         Default    Black         ░▒▓'
    'user_segment            Black      Yellow'
    'time_segment            Purple     Black'
    'ssh_segment             Black      Red'
    'git_segment             Green      Black'
    'path_segment            Blue       BoldWhite'
    'newline_segment'
    'literal_segment         Default    BoldBlack     ╰─'
    'prompt_segment          Default    BoldBlack'
    'empty_segment'
)

# Segments Options
PL_PATH_TRIM=0             # 0 Full path, 1, Current, 2+ trim level
PL_TIME_SHOW_SECONDS=false
PL_USER_SHOW_HOST=true
PL_USER_USE_IP=false
PL_SSH_SHOW_HOST=true
PL_SSH_USE_IP=true
PL_GIT_AHEAD=false
PL_GIT_MODIFIED=false
PL_GIT_STAGED=false
PL_GIT_CONFLICTS=false
PL_GIT_UNTRACKED=false
PL_GIT_STASH=false
PL_GIT_DIRTY=false
PL_USER_ROOT_BG=Black
PL_USER_ROOT_FG=BrightRed
PL_COMPACT=true

# redefine symbols using powerline glyphs
PL_SYMBOLS[hard_separator]=""
PL_SYMBOLS[soft_separator]=""

PL_SYMBOLS[git_branch]=""

