#!/usr/bin/env bash

function ian_pre_segment {
    local bg_color="$1"
    local fg_color="$2"
    local content="╭"

    #PS1+="$(segment_end "$fg_color" "$bg_color")"
    PS1+="$(segment_content "$fg_color" "$bg_color" "$content")"
    __last_color="None"
}
